-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbwqSQIVC7dWuFVLz
PG+H81AgfDY05PGEee3+vvhfgLWgCgYIKoZIzj0DAQehRANCAARRamAvBxOsAab+
HvZak7ir1e61SRD2kPhfCjKorAQ5VOeQpGnM8z9hiog7YZl1G+VsHio+jspaduci
g6krbJ7L
-----END PRIVATE KEY-----